### ISSUE TITLE
Version Dependency

### ISSUE THREAD

**Issue by halotroop2288** [GroovyMC/groovyduvet#1]
I'd like to use this on 1.18.2, but it seems like it's dependent on 1.19.3 for some reason. Why is that?
A language adapter doesn't really need to depend on any version-specific functions does it?

**Comment by lukebemish** [comment]
The core language adapters bit probably does not (or if it does, such a requirement is adaptable for sure) - however, GroovyDuvet is also a collection of wrapper APIs to groovy-ify common modding tasks and generally remove pain. These are by necessity version dependent. A good comparison would be how quilt kotlin libraries is version dependent.

**Comment by halotroop2288** [comment]
>A good comparison would be how quilt kotlin libraries is version dependent.

Yeah I don't get why QKL is version dependent either. I just know that Fabric language adapters never had that issue.

**Comment by lukebemish** [comment]
QKL, like groovyduvet, is *not just a language provider*. It's a language provider and a set of wrapper libraries; the latter of which, by definition, *have* to be linked to a version.

**Comment by lukebemish** [comment]
@halotroop2288 We now offer a probably-version-independent and separately updated publication of `groovyduvet-core`, which just provides the language adapter and JiJed stuff: https://github.com/GroovyMC/GroovyDuvetCore

**Comment by lukebemish** [comment]
(Note that this component will *not* be published on modrinth/curseforge)
